use_frameworks!

platform :ios, '8.0'

target 'LGEnglishTrainingFramework_Example' do
  pod 'LGEnglishTrainingFramework', :path => '../'

  target 'LGEnglishTrainingFramework_Tests' do
    inherit! :search_paths

    
  end
end
